version: '3.8'

services:
  proxy-subgraph:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
      - .:/app
      - /app/node_modules
    mem_limit: 4g
    memswap_limit: 4g
    cpus: '2'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: always
networks:
  default:
    external: true
    name: graphnet